version: "3.9"
services:
  nginx:
    build: ./docker/nginx
    container_name: nginx-container
    ports:
      - 80:80
    links:
      - php
    volumes:
      - ./:/var/www/html/

  php:
    build: ./docker/php
    container_name: php-container
    expose:
      - 9000
    links:
      - mysql
    volumes:
      - ./:/var/www/html/

  mysql:
    build: ./docker/mysql
    container_name: mysql-container
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: job
      MYSQL_USER: job
      MYSQL_PASSWORD: job-root
