openapi: 3.0.0
info:
  title: Job application
  description: Job application API doc
  version: 1.0.0

servers:
  - url: https://job.cijworld.com/api/v1
    description: Main v1 API server

tags:
  - name: register
    description: Register user
  - name: login
    description: Login user
  - name: category
    description: Category

paths:
  /login:
    post:
      tags:
        - login
      summary: Return auth token
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
            format: email
        - name: password
          in: query
          required: true
          schema:
            type: string
            format: password
        - name: remember_me
          in: query
          required: false
          schema:
            type: boolean
      responses:
        422:
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        200:
          description: Return token parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  token_type:
                    type: string
                    description: Token type
                    example: Bearer
                  token:
                    type: string
                    description: Token
                  expires_at:
                    type: integer
                    description: Token expires time

  /register:
    description: Register user action
    post:
      tags:
        - register
      responses:
        200:
          description: Successful register
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /logout:
    description: Logout user action
    post:
      tags:
        - login
      security:
        - bearerAuth: []
      responses:
        200:
          description: Logout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        401:
          $ref: '#/components/responses/UnauthorizedError'

  /category:
    description: Category list
    get:
      tags:
        - category
      security:
        - bearerAuth: []
      responses:
        200:
          description: List of category
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        title:
                          type: string
                        children:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: integer
                              title:
                                type: string
        401:
          $ref: '#/components/responses/UnauthorizedError'

components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
          description: Error message
        errors:
          type: array
          description: Array of fields
          items:
            type: object
            description: Array of errors
            items:
              type: string

  responses:
    UnauthorizedError:
      description: Access token is missing or invalid

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
